version: '3.8'

services:
  fifo-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - fifo-network

  fifo-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - fifo-server
    networks:
      - fifo-network
    environment:
      - FIFO_SERVER_ENDPOINT=tcp://fifo-server:5555

networks:
  fifo-network:
    driver: bridge